"""points desc and tasks

Revision ID: 65e9cbe51d82
Revises: fd4b32d4ef8b
Create Date: 2025-10-04 07:29:14.773335

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65e9cbe51d82"
down_revision: Union[str, None] = "fd4b32d4ef8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams", sa.Column("Description", sa.Text(), nullable=True))
    op.add_column("teams", sa.Column("tasks_completed", sa.Integer(), nullable=True))
    op.add_column("teams", sa.Column("points", sa.Integer(), nullable=True))
    op.drop_column("teams", "city")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teams", sa.Column("city", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_column("teams", "points")
    op.drop_column("teams", "tasks_completed")
    op.drop_column("teams", "Description")
    # ### end Alembic commands ###
