"""points desc and tasks fix

Revision ID: a644275ac3c6
Revises: 65e9cbe51d82
Create Date: 2025-10-04 08:01:19.716856

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a644275ac3c6"
down_revision: Union[str, None] = "65e9cbe51d82"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams", sa.Column("description", sa.Text(), nullable=True))
    op.drop_column("teams", "Description")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teams", sa.Column("Description", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_column("teams", "description")
    # ### end Alembic commands ###
