"""Added number of teammembers

Revision ID: fd4b32d4ef8b
Revises: 4b3461dd3cdc
Create Date: 2025-09-05 16:42:44.148855

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd4b32d4ef8b"
down_revision: Union[str, None] = "4b3461dd3cdc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams", sa.Column("number_of_members", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("teams", "number_of_members")
    # ### end Alembic commands ###
