"""added temp fields

Revision ID: a3ffe2817973
Revises: 0d7d498a3de4
Create Date: 2025-11-13 16:39:34.381084

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a3ffe2817973"
down_revision: Union[str, None] = "0d7d498a3de4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("temp_name", sa.String(length=50), nullable=True))
    op.add_column(
        "users", sa.Column("temp_password", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column(
            "temp_role",
            sa.Enum("STUDENT", "TEACHER", "MODER", name="user_role_enum"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "temp_role")
    op.drop_column("users", "temp_password")
    op.drop_column("users", "temp_name")
    # ### end Alembic commands ###
