"""add_user_role_teacher_or_blyat_not

Revision ID: d072bb4d8db5
Revises: f0a62a3b1e9a
Create Date: 2025-09-09 10:32:26.412025

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d072bb4d8db5"
down_revision: Union[str, None] = "f0a62a3b1e9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE TYPE user_role_enum AS ENUM ('STUDENT', 'TEACHER')")

    # Потом добавляем колонку
    op.add_column(
        "users",
        sa.Column(
            "role", sa.Enum("STUDENT", "TEACHER", name="user_role_enum"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
