"""added temp fields for login

Revision ID: ddde79c77f6d
Revises: a3ffe2817973
Create Date: 2025-11-13 17:34:35.852227

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ddde79c77f6d"
down_revision: Union[str, None] = "a3ffe2817973"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("temp_login", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "temp_login")
    # ### end Alembic commands ###
