"""added is learned

Revision ID: 88b6bbbd3677
Revises: 1ce288bd0b4a
Create Date: 2025-10-05 21:54:49.698460

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "88b6bbbd3677"
down_revision: Union[str, None] = "1ce288bd0b4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_profile", sa.Column("is_learned", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profile", "is_learned")
    # ### end Alembic commands ###
