"""init zvezda tables with orgs

Revision ID: 47ca50b46bc4
Revises: 588f95ae6add
Create Date: 2025-10-04 03:49:10.439921

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "47ca50b46bc4"
down_revision: Union[str, Sequence[str], None] = "588f95ae6add"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects", sa.Column("organization_name", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "organization_name")
    # ### end Alembic commands ###
