"""fix

Revision ID: 7d43da4d32c7
Revises: 47ca50b46bc4
Create Date: 2025-10-04 08:08:37.378794

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "7d43da4d32c7"
down_revision: Union[str, Sequence[str], None] = "47ca50b46bc4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
