"""create submission table

Revision ID: 2c1d1e568288
Revises: 74518d77a0c7
Create Date: 2025-10-08 15:15:13.497755

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c1d1e568288"
down_revision: Union[str, None] = "74518d77a0c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "courses", "description", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.drop_column("courses", "is_completed")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "courses",
        sa.Column("is_completed", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "courses", "description", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###
