"""update courses table fields

Revision ID: 74518d77a0c7
Revises: 819227276943
Create Date: 2025-10-05 19:13:07.117805

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "74518d77a0c7"
down_revision: Union[str, None] = "819227276943"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "courses", sa.Column("description", sa.String(length=255), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courses", "description")
    # ### end Alembic commands ###
